<div data-bind="scope: 'randomReview'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "randomReview": {
                        "component": "Training4point4_Test/js/review",
                        "config": {
                            "template": "Training4point4_Test/review",
                            "url": <?= json_encode($block->getUrl('training4point4_test/index/index')) ?>
                        }
                    }
                }
            }
        }
}
</script>